'use client';
import Link from '@/components/static-link';
import { useState, useEffect } from 'react';
import { motion, AnimatePresence, useReducedMotion } from 'framer-motion';
import { ShoppingBag, Menu, X } from 'lucide-react';
import { useShop } from './shop-provider';
const links = [{ name: 'New Drops', href: '/collections/new-drops/' },{ name: 'T-Shirts', href: '/#drop' },{ name: 'Collections', href: '/#collections' },{ name: 'About', href: '/#about' },{ name: 'FAQ', href: '/#faq' }];
export default function Navigation() {
 const [scrolled,setScrolled]=useState(false),[menu,setMenu]=useState(false); const shop=useShop(), reduced=useReducedMotion();
 useEffect(()=>{ const onScroll=()=>setScrolled(window.scrollY>80); onScroll(); window.addEventListener('scroll',onScroll,{passive:true}); return()=>window.removeEventListener('scroll',onScroll); },[]);
 useEffect(()=>{ if(!menu)return; const prior=document.activeElement as HTMLElement; const old=document.body.style.overflow; document.body.style.overflow='hidden'; const root=document.getElementById('mobile-menu'); const list=()=>Array.from(root?.querySelectorAll<HTMLElement>('a,button')||[]); list()[0]?.focus(); const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);if(e.key==='Tab'){const a=list();if(e.shiftKey&&document.activeElement===a[0]){e.preventDefault();a[a.length-1]?.focus();}else if(!e.shiftKey&&document.activeElement===a[a.length-1]){e.preventDefault();a[0]?.focus();}}};document.addEventListener('keydown',onKey);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',onKey);prior?.focus();};},[menu]);
 const count=shop.items.reduce((n,i)=>n+i.quantity,0);
 return <><a href="#main" className="skip-link">Skip to content</a><motion.header className={`navigation ${scrolled?'floating':''}`} initial={reduced?false:{y:-20,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:1.3,duration:.6}}><Link href="/" className="logo" aria-label="SK GARMENTS home">SK<span>GARMENTS</span></Link><nav aria-label="Main navigation" className="desktop-nav">{links.map(l=><Link key={l.name} href={l.href}>{l.name}</Link>)}</nav><div className="nav-actions"><button className="bag-button" onClick={shop.openBag} aria-label={`Open bag, ${count} items`}><ShoppingBag size={18}/><span>{count.toString().padStart(2,'0')}</span></button><Link className="nav-shop" href="/collections/new-drops/">SHOP</Link><button className="mobile-menu-button icon-button" aria-label="Open navigation menu" aria-expanded={menu} onClick={()=>setMenu(true)}><Menu/></button></div></motion.header><AnimatePresence>{menu && <motion.div id="mobile-menu" className="mobile-menu" role="dialog" aria-modal="true" aria-label="Navigation menu" initial={{clipPath:'inset(0 0 100% 0)'}} animate={{clipPath:'inset(0 0 0% 0)'}} exit={{clipPath:'inset(0 0 100% 0)'}} transition={{duration:reduced?0:.45}}><div className="mobile-menu-top"><Link className="logo" href="/" onClick={()=>setMenu(false)}>SK<span>GARMENTS</span></Link><button className="icon-button" aria-label="Close navigation menu" onClick={()=>setMenu(false)}><X/></button></div><nav>{links.map((l,i)=><motion.div key={l.name} initial={{y:30,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:.1+i*.06}}><Link href={l.href} onClick={()=>setMenu(false)}><small>0{i+1}</small>{l.name}</Link></motion.div>)}</nav><p>Wear what feels like you.</p></motion.div>}</AnimatePresence><Link className="floating-shop" href="/collections/new-drops/">SHOP NOW <span>✳</span></Link></>;
}