'use client';
import { createContext, useContext, useEffect, useState, useRef, ReactNode } from 'react';
import { products, priceLabel, Product } from '@/data/products';
import { site } from '@/data/site';
import { AnimatePresence, motion, MotionConfig } from 'framer-motion';
import { X, Minus, Plus, ShoppingBag, Check, Copy } from 'lucide-react';
import Link from '@/components/static-link';
import Garment from './garment';
type Item = { slug: string; size: string; color: string; quantity: number };
type Shop = { items: Item[]; add: (p: Product, size: string, color: string) => void; openBag: () => void; openInfo: (title: string, text: string) => void };
const Context = createContext<Shop | null>(null);
export const useShop = () => useContext(Context)!;
export function Dialog({ title, close, children, side = false }: { title: string; close: () => void; children: ReactNode; side?: boolean }) {
 const closeRef=useRef(close); closeRef.current=close;
 useEffect(() => { const prior = document.activeElement as HTMLElement | null; const overflow = document.body.style.overflow; document.body.style.overflow = 'hidden'; const node = document.getElementById('active-dialog'); const focusables = () => Array.from(node?.querySelectorAll<HTMLElement>('a[href],button:not([disabled]),input,select,textarea,[tabindex="0"]') || []); focusables()[0]?.focus(); const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') closeRef.current(); if (e.key === 'Tab') { const f = focusables(); if (!f.length) return; if(e.shiftKey && document.activeElement === f[0]) { e.preventDefault(); f[f.length-1].focus(); } else if(!e.shiftKey && document.activeElement === f[f.length-1]) { e.preventDefault(); f[0].focus(); } } }; document.addEventListener('keydown',handler); return () => { document.body.style.overflow = overflow; document.removeEventListener('keydown',handler); prior?.focus(); }; }, []);
 return <motion.div className="dialog-overlay" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={close}><motion.section id="active-dialog" className={`dialog ${side ? 'bag-dialog' : ''}`} role="dialog" aria-modal="true" aria-label={title} initial={side ? { x: '100%' } : { y: 24, opacity: 0 }} animate={{ x: 0, y: 0, opacity: 1 }} exit={side ? { x: '100%' } : { y: 24, opacity: 0 }} onClick={e => e.stopPropagation()}><div className="dialog-heading"><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="Close dialog"><X/></button></div>{children}</motion.section></motion.div>;
}
export default function ShopProvider({ children }: { children: ReactNode }) {
 const [items, setItems] = useState<Item[]>([]), [ready, setReady] = useState(false), [bag, setBag] = useState(false), [info, setInfo] = useState<{ title: string; text: string } | null>(null), [copied, setCopied] = useState(false), [copyError,setCopyError] = useState(false);
 useEffect(() => { try { const saved = JSON.parse(localStorage.getItem('sk-bag') || '[]'); if(Array.isArray(saved)) setItems(saved.filter(i => products.some(p=>p.slug===i.slug && p.sizes.includes(i.size) && p.colors.includes(i.color)) && Number.isInteger(i.quantity) && i.quantity>0).map(i=>({...i,quantity:Math.min(i.quantity,99)}))); } catch {} setReady(true); }, []);
 useEffect(() => { if(ready) try { localStorage.setItem('sk-bag', JSON.stringify(items)); } catch {} },[items,ready]);
 const add = (p: Product, size: string, color: string) => { setItems(previous=>{ const index = previous.findIndex(i=>i.slug===p.slug && i.size===size && i.color===color); return index < 0 ? [...previous,{slug:p.slug,size,color,quantity:1}] : previous.map((i,n)=>n===index ? {...i,quantity:Math.min(99,i.quantity+1)} : i); }); setBag(true); };
 useEffect(()=>{setCopied(false);setCopyError(false);},[items]);
 const message = `Hi SK GARMENTS, I’d like to enquire about:\n${items.map(i=>`${products.find(p=>p.slug===i.slug)?.name} — ${i.color}, size ${i.size}, quantity ${i.quantity}`).join('\n')}\nPlease confirm availability, final price, and shipping options.`;
 const checkout = site.contact.externalCheckout || (site.contact.whatsapp ? `https://wa.me/${site.contact.whatsapp.replace(/\D/g,'')}?text=${encodeURIComponent(message)}` : site.contact.email ? `mailto:${site.contact.email}?subject=SK%20GARMENTS%20product%20enquiry&body=${encodeURIComponent(message)}` : '');
 const total = items.reduce((n,i)=>n+((products.find(p=>p.slug===i.slug)?.price ?? 0)*i.quantity),0);
 return <MotionConfig reducedMotion="user"><Context.Provider value={{ items, add, openBag:()=>setBag(true), openInfo:(title,text)=>setInfo({title,text}) }}>{children}<AnimatePresence>{bag && <Dialog title={`YOUR BAG (${items.reduce((n,i)=>n+i.quantity,0)})`} close={()=>setBag(false)} side>{items.length ? <><div className="bag-items">{items.map((item,index)=>{ const p=products.find(p=>p.slug===item.slug)!; return <div className="bag-item" key={`${item.slug}-${item.color}-${item.size}`}><Link href={`/products/${p.slug}/`} onClick={()=>setBag(false)}><Garment color={item.color} graphic={p.graphic}/></Link><div><Link href={`/products/${p.slug}/`} onClick={()=>setBag(false)}><h3>{p.name}</h3></Link><p>{item.color} / {item.size}</p><p>{priceLabel(p)}</p><div className="quantity"><button aria-label={`Decrease quantity of ${p.name}`} onClick={()=>setItems(items.map((i,n)=>n===index?{...i,quantity:i.quantity-1}:i).filter(i=>i.quantity>0))}><Minus size={14}/></button><span>{item.quantity}</span><button disabled={item.quantity>=99} aria-label={`Increase quantity of ${p.name}`} onClick={()=>setItems(items.map((i,n)=>n===index?{...i,quantity:i.quantity+1}:i))}><Plus size={14}/></button><button className="remove" onClick={()=>setItems(items.filter((_,n)=>n!==index))}>Remove</button></div></div></div>; })}</div><div className="bag-summary"><p>{items.every(i=>products.find(p=>p.slug===i.slug)?.price!==null) ? `Subtotal ₹${total.toLocaleString('en-IN')}` : 'Final prices confirmed on enquiry.'}</p><p className="small-copy">This is an enquiry, not a confirmed order.</p>{checkout ? <a className="button dark full" href={checkout} target="_blank" rel="noreferrer">Send enquiry</a> : <><p className="small-copy">Ordering contact is being added. Copy your enquiry to keep your selections.</p><button className="button dark full" onClick={async()=>{ try { await navigator.clipboard.writeText(message); setCopied(true);setCopyError(false); } catch { setCopied(false);setCopyError(true); } }}>{copied ? <Check size={16}/> : <Copy size={16}/>} {copied?'Enquiry copied':'Copy enquiry'}</button>{copyError&&<div className="copy-fallback"><p role="status" className="small-copy">Copy is unavailable. Select and copy your draft below.</p><textarea readOnly value={message} rows={5} aria-label="Your enquiry draft"/></div>}</>}</div></> : <div className="empty-bag"><ShoppingBag size={48}/><h3>Good things belong here.</h3><p>Find a tee that feels like you.</p><Link className="button dark" href="/collections/new-drops/" onClick={()=>setBag(false)}>Explore the drop</Link></div>}</Dialog>}{info && <Dialog title={info.title} close={()=>setInfo(null)}><p className="info-copy">{info.text}</p></Dialog>}</AnimatePresence></Context.Provider></MotionConfig>;
}